dataset:
  type: kitti
  common_args: &dataset_common_args
    basedir: ./data/kitti/
    cam_id: 2
    meta_json: 'data_len.json'
    skip_frame: 1
    voxel_size: null
    min_dist: 0.1
    skip_point: 1
    pcd_sample_num: 8192
    resize_size: [224, 448]
    extend_ratio: [2.5, 2.5]

  train:
    dataset:
      train:
        base:
          seqs: ['00','02','03','04','05','06','07','08','10','12']
          <<: *dataset_common_args
        main: &train_main
          max_deg: &max_deg 15
          max_tran: &max_tran 0.15
          mag_randomly: true
      val:
        base:
          seqs: ['16','17','18']
          <<: *dataset_common_args
        main:
          max_deg: *max_deg
          max_tran: *max_tran
          mag_randomly: true
    dataloader:
      common_args: &dataloader_common_args
        num_workers: 4
        pin_memory: true
      args:
        batch_sampler:
          dataset_len: 1024
          num_samples: 16
        <<: *dataloader_common_args
      val_args:
        batch_sampler:
          dataset_len: 512
          num_samples: 16
        <<: *dataloader_common_args
  test:
    common_main: &test_common_main
      max_deg: *max_deg
      max_tran: *max_tran
      mag_randomly: true
    dataset:
      - name: seq_16
        base:
          seqs: ['16']
          <<: *dataset_common_args
        main:
          <<: *test_common_main
          file: cache/kitti_large/test_16.txt
      - name: seq_17
        base:
          seqs: ['17']
          <<: *dataset_common_args
        main:
          <<: *test_common_main
          file: cache/kitti_large/test_17.txt
      - name: seq_18
        base:
          seqs: ['18']
          <<: *dataset_common_args
        main:
          <<: *test_common_main
          file: cache/kitti_large/test_18.txt
      
    dataloader:
      batch_size: 16
      shuffle: false
      drop_last: false
      pin_memory: true
      num_workers: 8


