dataset:
  type: kitti
  common_args: &dataset_common_args
    basedir: ./data/kitti/
    cam_id: 2
    meta_json: 'data_len.json'
    skip_frame: 1
    voxel_size: null
    min_dist: 0.1
    skip_point: 1
    resize_size: [224, 448]
    extend_ratio: [2.5, 2.5]
  train:
    dataset:
      train:
        base:
          seqs: ['00','02','03','04','05','06','07','08','10','12','21']
          <<: *dataset_common_args
          pcd_sample_num: &train_sample_num 8192
        main: &train_main
          max_deg: &max_deg 15
          max_tran: &max_tran 0.15
          min_deg: &min_deg 0.0
          min_tran: &min_tran 0.0
          mag_randomly: true
      val:
        base:
          seqs: ['11','17','20']
          <<: *dataset_common_args
          pcd_sample_num: *train_sample_num
        main:
          <<: *train_main
    dataloader:
      common_args: &dataloader_common_args
        num_workers: 4
        pin_memory: true
      args:
        batch_sampler:
          dataset_len: 1024
          num_samples: 16
        <<: *dataloader_common_args
      val_args:
        batch_sampler:
          dataset_len: 256
          num_samples: 16
        shuffle: false
        <<: *dataloader_common_args
  test:
    test_common: &test_main
      max_deg: 15
      max_tran: 0.15
      min_deg: 0.0
      min_tran: 0.0
      mag_randomly: true
    dataset:
      - name: seq_13
        base:
          seqs: ['13']
          <<: *dataset_common_args
          pcd_sample_num: &test_sample_num 8192
        main:
          <<: *test_main
          file: cache/kitti_r15_t0.15/test_13.txt
      - name: seq_14
        base:
          seqs: ['14']
          <<: *dataset_common_args
          pcd_sample_num: *test_sample_num
        main:
          <<: *test_main
          file: cache/kitti_r15_t0.15/test_14.txt
      - name: seq_15
        base:
          seqs: ['15']
          <<: *dataset_common_args
          pcd_sample_num: *test_sample_num
        main:
          <<: *test_main
          file: cache/kitti_r15_t0.15/test_15.txt
      - name: seq_16
        base:
          seqs: ['16']
          <<: *dataset_common_args
          pcd_sample_num: *test_sample_num
        main:
          <<: *test_main
          file: cache/kitti_r15_t0.15/test_16.txt
      - name: seq_18
        base:
          seqs: ['18']
          <<: *dataset_common_args
          pcd_sample_num: *test_sample_num
        main:
          <<: *test_main
          file: cache/kitti_r15_t0.15/test_18.txt
    dataloader:
      batch_size: 16
      shuffle: false
      drop_last: false
      pin_memory: true
      num_workers: 4

  test_time:
    dataset:
      base:
        seqs: ['13','14','15','16','18']
        <<: *dataset_common_args
        pcd_sample_num: *test_sample_num
      main:
        <<: *test_main
        file:
          - cache/kitti_r15_t0.15/test_13.txt
          - cache/kitti_r15_t0.15/test_14.txt
          - cache/kitti_r15_t0.15/test_15.txt
          - cache/kitti_r15_t0.15/test_16.txt
          - cache/kitti_r15_t0.15/test_18.txt
    dataloader:
      batch_size: 1
      shuffle: false
      drop_last: false
      pin_memory: true
      num_workers: 0


